In [ ]:
# Step 1: Import Libraries and Load the Model
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import load_model

# 2️⃣ Load IMDb Word Index
word_index = imdb.get_word_index()
reverse_word_index = {value: key for key, value in word_index.items()}

# 3️⃣ Load the Saved Model
model = load_model("simple_RNN_IMDb.h5")
model.summary()
# Model: "sequential_2"
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
# ┃ Layer (type)                     ┃ Output Shape               ┃     Param #   ┃
# ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
# │ embedding_2 (Embedding)          │ (32, 500, 128)             │   1,280,000   │
# ├──────────────────────────────────┼────────────────────────────┼───────────────┤
# │ simple_rnn_2 (SimpleRNN)         │ (32, 128)                  │      32,896   │
# ├──────────────────────────────────┼────────────────────────────┼───────────────┤
# │ dense_2 (Dense)                  │ (32, 1)                    │         129   │
# └──────────────────────────────────┴────────────────────────────┴───────────────┘

# ✔️ Model Weights & Configurations
model.get_weights()
# [array([[ 0.4596259 ,  0.53319734,  0.55423784, ...,  0.43775293,
#          -0.4507563 , -0.20143569],
#         [ 0.02310601,  0.04642281,  0.02657712, ...,  0.01580666,
#          -0.05199308, -0.02238323],
#         [ 0.20506571,  0.17491959,  0.18800467, ...,  0.0693355 ,
#          -0.01409165, -0.07371497],
#         ...,
#         [-0.03629489, -0.01677965,  0.0182996 , ...,  0.0091647 ,
#           0.02196272, -0.04208431],
#         [ 0.02290117, -0.03122706, -0.03311079, ...,  0.026536  ,
#           0.04450313,  0.02539615],
#         [-0.11487858,  0.07086714,  0.09391264, ..., -0.02742145,
#           0.10885108,  0.0566919 ]], dtype=float32),
#  array([[ 0.06207999,  0.07406113, -0.08354215, ...,  0.07127541,
#          -0.09075762, -0.0804019 ],
#         [ 0.01369929, -0.11487575, -0.11657262, ..., -0.01235133,
#          -0.01451336,  0.15060797],
#         [-0.0343852 , -0.07726757,  0.04736179, ..., -0.03889079,
#          -0.15673397, -0.09135915],
#         ...,
#         [-0.09491704,  0.07561485, -0.01364365, ...,  0.07883184,
#          -0.04939375, -0.09725694],
#         [-0.11242743, -0.07432204,  0.11568087, ...,  0.02050661,
#          -0.00629957,  0.00289705],
#         [ 0.16011922, -0.05628216, -0.13047743, ...,  0.17677419,
#           0.1470423 , -0.08410051]], dtype=float32),
#  array([[ 0.07011421, -0.03297521, -0.02213165, ..., -0.13795307,
#          -0.05432294, -0.01141085],
#         [-0.11215336, -0.06722376,  0.06517976, ...,  0.02880199,
#          -0.10194683, -0.02009553],
#         [-0.08161753,  0.09639953, -0.08485168, ..., -0.18143149,
#          -0.05408657,  0.20259352],
#         ...,
#         [-0.03064019, -0.02397398,  0.02337803, ..., -0.22316183,
#           0.06745446,  0.28160405],
#         [ 0.03248002, -0.03638319, -0.08645554, ...,  0.06876045,
#           0.24742442, -0.12268136],
#         [-0.05915767, -0.07498628, -0.02860353, ...,  0.03903188,
#          -0.09966922, -0.1086898 ]], dtype=float32),
#  array([ 0.0233273 , -0.00968308, -0.002227  , -0.04168632, -0.03153659,
#          0.04324037,  0.0294568 , -0.05147198, -0.03963124,  0.02909257,
#          0.04256338,  0.02325991, -0.03296885, -0.01728713,  0.03084679,
#         -0.03014611, -0.02456368, -0.00950514, -0.02106467, -0.00566297,
#         -0.01909167,  0.00711027, -0.00305642, -0.02931846, -0.01865956,
#         -0.03063713, -0.02425206,  0.00730712, -0.04781404, -0.03717393,
#         -0.02624389, -0.01761279, -0.00733354, -0.01594612,  0.01467569,
#         -0.0666431 , -0.019819  , -0.04319379,  0.0080432 , -0.04358533,
#          0.00998127, -0.0072085 , -0.04344559,  0.01601157,  0.03799264,
#         -0.02885599,  0.04199192,  0.00625391,  0.00997626,  0.04151207,
#         -0.06420345,  0.01443399,  0.00455073, -0.03690003, -0.03274364,
#         -0.00419351, -0.00157107, -0.02804569, -0.02834101, -0.00861882,
#         -0.02972055, -0.01077789, -0.0435359 ,  0.02745282, -0.00165685,
#         -0.02933095, -0.0285998 ,  0.02088291, -0.028598  , -0.03390975,
#          0.00234892, -0.04027199, -0.02405254,  0.00176036,  0.0530137 ,
#         -0.0170425 , -0.04358249, -0.02145463, -0.03912302,  0.02971506,
#         -0.01237154, -0.03046837,  0.00277285, -0.04267131, -0.03276147,
#         -0.03098065,  0.01287637, -0.02336248, -0.05155027,  0.02267224,
#         -0.02189099, -0.03101695, -0.00797956, -0.01183891, -0.03547668,
#          0.02351721, -0.04956992,  0.06467333, -0.02998889, -0.01942777,
#         -0.03104826,  0.00315068,  0.01533143, -0.04526998,  0.00753492,
#          0.06947016,  0.0037906 , -0.02795827,  0.02288711, -0.03991408,
#          0.02580469,  0.01877258, -0.02222668, -0.04476491, -0.05266887,
#         -0.03594896,  0.02484092, -0.01829875, -0.01946704,  0.03655313,
#         -0.03938689,  0.02024437,  0.03635949,  0.00080822,  0.03023203,
#         -0.03460443, -0.03357026, -0.01598015], dtype=float32),
#  array([[-0.04532278],
#         [ 0.12606774],
#         [-0.06392212],
#         [ 0.05988648],
#         [ 0.084401  ],
#         [-0.18129162],
#         [-0.2536244 ],
#         [ 0.13940753],
#         [-0.02512877],
#         [ 0.01533136],
#         [ 0.170873  ],
#         [-0.20930058],
#         [-0.15778749],
#         [ 0.15541586],
#         [-0.06309807],
#         [-0.18870409],
#         [-0.08083982],
#         [-0.02000136],
#         [ 0.08256276],
#         [ 0.17073992],
#         [-0.21854407],
#         [-0.08173376],
#         [ 0.37896463],
#         [ 0.1670677 ],
#         [-0.23829153],
#         [ 0.04613155],
#         [ 0.02278428],
#         [-0.08767835],
#         [-0.09155211],
#         [ 0.01266565],
#         [ 0.02620401],
#         [ 0.00506826],
#         [ 0.1389305 ],
#         [ 0.06271034],
#         [ 0.11934235],
#         [ 0.15285017],
#         [ 0.01799884],
#         [ 0.03328443],
#         [ 0.15886118],
#         [-0.15632807],
#         [-0.21515827],
#         [-0.04552786],
#         [-0.27006996],
#         [ 0.10488717],
#         [ 0.19289614],
#         [ 0.14126736],
#         [-0.16064508],
#         [-0.15069708],
#         [ 0.15616144],
#         [-0.05671411],
#         [ 0.27253363],
#         [ 0.01622418],
#         [-0.19435197],
#         [ 0.15478985],
#         [-0.0653083 ],
#         [-0.11294877],
#         [-0.05695173],
#         [-0.15549338],
#         [ 0.02968873],
#         [ 0.07808764],
#         [-0.07276581],
#         [ 0.00356239],
#         [-0.19802321],
#         [-0.00739092],
#         [-0.1993485 ],
#         [ 0.11689998],
#         [ 0.07174439],
#         [ 0.0588005 ],
#         [-0.1376429 ],
#         [ 0.02609351],
#         [-0.20898049],
#         [-0.08309633],
#         [ 0.12747931],
#         [ 0.17595   ],
#         [-0.11972861],
#         [-0.14250614],
#         [ 0.18921755],
#         [-0.2742901 ],
#         [ 0.01290718],
#         [ 0.04792801],
#         [-0.13367786],
#         [ 0.16942933],
#         [ 0.16592446],
#         [ 0.07487311],
#         [ 0.05038485],
#         [ 0.18829273],
#         [-0.05009097],
#         [-0.13773058],
#         [ 0.08932133],
#         [ 0.00499359],
#         [-0.00496665],
#         [ 0.09468246],
#         [-0.01797937],
#         [ 0.2405717 ],
#         [ 0.24116941],
#         [ 0.07971925],
#         [ 0.09729208],
#         [ 0.03295109],
#         [-0.13001335],
#         [ 0.06066846],
#         [ 0.00901129],
#         [-0.17975758],
#         [ 0.0318459 ],
#         [ 0.20684268],
#         [-0.05560631],
#         [-0.1565269 ],
#         [-0.31902328],
#         [ 0.11243184],
#         [ 0.08998556],
#         [ 0.00960341],
#         [-0.02482632],
#         [ 0.18429719],
#         [-0.25622934],
#         [-0.21127015],
#         [ 0.1044439 ],
#         [ 0.21602124],
#         [-0.13360125],
#         [ 0.13895386],
#         [ 0.34373012],
#         [-0.11517696],
#         [ 0.06074231],
#         [ 0.2452877 ],
#         [-0.10334561],
#         [ 0.11837602],
#         [ 0.15323645],
#         [-0.12951005],
#         [ 0.09453125],
#         [ 0.00719355]], dtype=float32),
#  array([0.24527277], dtype=float32)]

# ✔️ Helper Function
# Function to decode reviews
def decode_review(encoded_review):
    return ' '.join([reverse_word_index.get(i - 3, '?') for i in encoded_review])

# Function to preprocess user input
def preprocess_text(text):
    words = text.lower().split()
    encoded_review = [word_index.get(word, 2) + 3 for word in words]
    padded_review = sequence.pad_sequences([encoded_review], maxlen=500)
    return padded_review

### Prediction function
def predict_sentiment(review):
    preprocessed_input = preprocess_text(review)
    prediction = model.predict(preprocessed_input)
    sentiment = 'Positive' if prediction[0][0] > 0.5 else 'Negative'
    return sentiment, prediction[0][0]

# Step 4: User Input and Prediction
# Example review for prediction
example_review = "The movie was good."
sentiment,score = predict_sentiment(example_review)
# Print the results
print(f'Review: {example_review}')
print(f'Sentiment: {sentiment}')
print(f'Prediction Score: {score}')


# Review: The movie was good.
# Sentiment: Positive
# Prediction Score: 0.5012974143028259

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (32, 500, 128)         │     1,280,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (32, 128)              │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (32, 1)                │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,313,027 (5.01 MB)

 Trainable params: 1,313,025 (5.01 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step
Review: The movie was good.
Sentiment: Positive
Prediction Score: 0.5012974143028259
